/** Mirrors backend/src/config/recordTypes.js -- drives the clinical-record tabs/forms. */
export const RECORD_TYPES = {
  "health-assessment": {
    label: "Health Assessment",
    singular: "Health Assessment",
    table: "health_assessments",
    dateField: "assessment_date",
    dateLabel: "Assessment date",
    fields: {
      diagnosis: { label: "Condition", type: "text", required: true, primary: true },
      description: { label: "Description", type: "textarea", required: false, column: true },
      status: { label: "Status", type: "select", required: true, column: true, options: { active: "Active", resolved: "Resolved" } },
      medication: { label: "Medication", type: "text", required: false, column: true },
      remarks: { label: "Remarks", type: "textarea", required: false, column: true },
    },
  },
  "Vital-signs": {
    label: "Vital Signs",
    singular: "Vital Signs Record",
    table: "vital_signs",
    dateField: "recorded_at",
    dateLabel: "Date recorded",
    fields: {
      blood_pressure: { label: "Blood Pressure", type: "text", required: true, primary: true },
      temperature: { label: "Temperature", type: "text", required: true, column: true },
      pulse_rate: { label: "Pulse Rate", type: "text", required: true, column: true },
      respiratory_rate: { label: "Respiratory Rate (breaths/min)", type: "text", required: true, column: true },
      height_cm: { label: "Height (cm)", type: "text", required: false, column: true },
      weight_kg: { label: "Weight (kg)", type: "text", required: false, column: true },
      bmi: { label: "Body Mass Index", type: "number", required: true, column: true },
      oxygen_saturation: { label: "Oxygen Saturation (Sp02 %)", type: "number", required: true, column: true },
      pain_score: { label: "Pain Score (0-10)", type: "number", required: true, column: true },
    },
  },
  "midwfie-notes": {
    label: "Midwife Notes",
    singular: "Midwife Note",
    table: "midwife_notes",
    dateField: "consultation_date",
    dateLabel: "Consultation date",
    fields: {
      note: { label: "Notes", type: "textarea", required: true, column: true },
    },
  },
  "medical-history": {
    label: "Medical History",
    singular: "Medical History Entry",
    table: "medical_histories",
    dateField: "recorded_at",
    dateLabel: "Date recorded",
    fields: {
       past_illnesses: { label: "Past Illnesses", type: "textarea", required: false, column: true },
       chronic_conditions: { label: "Chronic Conditions", type: "textarea", required: false, column: true },
       past_surgeries: { label: "Past Surgeries", type: "textarea", required: false, column: true },
       previous_hospitalizations: { label: "Previous Hospitalizations", type: "textarea", required: false, column: true },
       family_medical_history: { label: "Family Medical History", type: "textarea", required: false, column: true },
       immunization_status: { label: "Immunization Status", type: "textarea", required: false, column: true },
    },
  },
  Allergies: {
    label: "Allergies",
    singular: "Allergy",
    table: "Allergies",
    dateField: "recorded_at",
    dateLabel: "Date recorded",
    fields: {
       medication_allergies: { label: "Medication Allergies", type: "textarea", required: false, column: true },
       food_allergies: { label: "Food Allergies", type: "textarea", required: false, column: true },
       environmental_allergies: { label: "Environmental Allergies", type: "textarea", required: false, column: true},
       reaction: { label: "Reaction", type: "textarea", required: false, column: true},
       status: { label: "Status", type: "select", required: true, column: true, options: { active: "Active", resolved: "Resolved" } },
       remarks: { label: "Remarks", type: "textarea", required: false, column: true },
      },
    },
  },
};
